name : CICD Database Development To Production

on:
  push:
    branches:
      - main 

jobs:
  db_cicd: 
    name : Database CICD
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name : SSH Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: | 
            echo "Berhasil Terhubung Ke Server"